# Generated by Django 5.1 on 2024-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_task_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
